version: '3.9'
services:
  follower-database:
    image: postgres:14.2
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: "follower"

  follower-service:
    depends_on:
      - follower-database
    build:
      context: .
      dockerfile: follower-service/Dockerfile
    ports:
      - "8082:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      EnableSwagger: true

networks:
  default:
    name: twiddit
