# deployment
#
# set up a deployment for the user API.

apiVersion : apps/v1
kind: Deployment
metadata:
  name: "twiddit-3f49"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "twiddit-3f49"
  template:
    metadata:
      labels:
        app: "twiddit-3f49"
    spec:
      containers:
        - name: "twiddit-3f49"
          image: "twiddit2.azurecr.io/twiddit"
          ports:
          - containerPort: 80

---
# service

apiVersion: v1
kind: Service
metadata:
    name: "twiddit-3f49"
    labels:
        app: "twiddit-3f49"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "twiddit-3f49"

---
# ingress
#
# Sets up an ingress to route traffic to the user service

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "twiddit-3f49"
    labels:
        app: "twiddit-3f49"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        - host: twiddit.5fd06ac12e634d9096be.uksouth.aksapp.io
          http:
            paths:
            - path: /api/followers
              pathType: Prefix
              backend:
                service:
                  name: "twiddit-3f49"
                  port:
                    number: 80