apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "twidditcluster-58fc"
    labels:
        app: "twidditcluster-58fc"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: default-twidditcluster-58fc.bdc33b62f0d9413db518.uksouth.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "twidditcluster-58fc"
                servicePort: 80